/**
 * Paragraph-id aliases, the serving half (reportsthatmatter-q8c).
 *
 * Ids are permalinks, and they move when the pipeline improves: a join merges
 * two paragraphs, a hybrid source re-ingests the report, a correction rewrites
 * an opening. Each report keeps `reports/<id>/aliases.yaml` (old id -> new id,
 * and renamed section slugs), generated by `pnpm aliases generate` from the
 * previous text against the new. Prerender copies it into the report's
 * `meta.json` as `paragraphAliases` / `sectionAliases`, so it is published and
 * rolled back with the content it describes, and the routes redirect a stale
 * `?p=` to the paragraph's new id and section.
 */

/** The alias fields of a pre-rendered meta.json; both absent on a report with none. */
export type AliasMeta = {
  paragraphToSection: Record<string, string>;
  paragraphAliases?: Record<string, string>;
  sectionAliases?: Record<string, string>;
};

/** Follows old -> new until it reaches something `isLive`; null on a dead end or a cycle. */
export function followAlias(aliases: Record<string, string>, id: string, isLive: (id: string) => boolean): string | null {
  const seen = new Set<string>();
  let at = id;
  while (!isLive(at)) {
    if (seen.has(at)) return null;
    seen.add(at);
    const next = Object.hasOwn(aliases, at) ? aliases[at] : undefined;
    if (!next) return null;
    at = next;
  }
  return at;
}

/**
 * Where a `?p=` id lives now: itself when current, else its alias target.
 * null when it is neither (the caller falls through to its usual handling).
 */
export function resolveParagraph(meta: AliasMeta, id: string): { id: string; slug: string } | null {
  if (Object.hasOwn(meta.paragraphToSection, id)) return { id, slug: meta.paragraphToSection[id] };
  const aliases = meta.paragraphAliases;
  if (!aliases) return null;
  const target = followAlias(aliases, id, (x) => Object.hasOwn(meta.paragraphToSection, x));
  return target ? { id: target, slug: meta.paragraphToSection[target] } : null;
}

/** A renamed section slug's current slug, or null when `slug` is current or unknown. */
export function resolveSection(meta: AliasMeta & { sections: { slug: string }[] }, slug: string): string | null {
  if (meta.sections.some((s) => s.slug === slug)) return null;
  const aliases = meta.sectionAliases;
  if (!aliases) return null;
  return followAlias(aliases, slug, (x) => meta.sections.some((s) => s.slug === x));
}
