/**
 * The head of every report page, read the way a crawler reads it (reportsthatmatter-y2y8.4):
 * valid schema.org JSON-LD, one canonical URL per page, titles that lead with what people call
 * the report, and citation_* tags only for what we really serve.
 *
 * The JSON-LD is checked against a slice of the schema.org vocabulary
 * (tests/fixtures/schemaorg-subset.json, regenerated by scripts/schemaorg-subset.mjs):
 * every property must exist on its type or a parent, and every value must be of a type the
 * property accepts.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { parse } from "yaml";
import { app } from "../src/index";
import { citationMeta, reportJsonLd, sectionJsonLd, siteJsonLd } from "../src/lib/structured-data";
import { displayHeading, reportTitle, sectionTitle } from "../src/lib/titles";

type Vocab = { types: Record<string, string[]>; properties: Record<string, { domain: string[]; range: string[] }> };
const vocab: Vocab = JSON.parse(readFileSync(join(import.meta.dirname, "fixtures/schemaorg-subset.json"), "utf8"));
const registry = parse(readFileSync(join(import.meta.dirname, "../reports/registry.yaml"), "utf8")).reports as Array<Record<string, any>>;

/** Every type and its ancestors. */
function lineage(type: string): string[] {
  const seen = new Set<string>();
  const walk = (name: string) => {
    if (seen.has(name)) return;
    seen.add(name);
    (vocab.types[name] ?? []).forEach(walk);
  };
  walk(type);
  return [...seen];
}

const ISO_DATE = /^\d{4}(-\d{2}(-\d{2})?)?$/;

/** Problems found in a JSON-LD node, as readable strings; empty when it is valid. */
function validate(node: any, path = "$"): string[] {
  const problems: string[] = [];
  const type = node["@type"];
  if (typeof type !== "string" || !vocab.types[type]) return [`${path}: unknown @type ${JSON.stringify(type)}`];
  const ancestry = lineage(type);

  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("@")) continue;
    const property = vocab.properties[key];
    if (!property) {
      problems.push(`${path}.${key}: not a schema.org property`);
      continue;
    }
    if (!property.domain.some((domain) => ancestry.includes(domain))) {
      problems.push(`${path}.${key}: not valid on ${type}`);
      continue;
    }
    for (const [i, item] of [value].flat().entries()) {
      const where = Array.isArray(value) ? `${path}.${key}[${i}]` : `${path}.${key}`;
      if (typeof item === "string") {
        // A bare URL where a Thing is expected is Google's documented form for ListItem.item.
        const urlForThing = property.range.includes("Thing") && /^https?:\/\//.test(item);
        if (!urlForThing && !property.range.some((r) => ["Text", "URL", "Date", "DateTime"].includes(r))) problems.push(`${where}: a string where ${property.range} is expected`);
        if (property.range.includes("URL") && !property.range.includes("Text") && !/^https?:\/\//.test(item)) problems.push(`${where}: not an absolute URL`);
        if (property.range.some((r) => r === "Date" || r === "DateTime") && !ISO_DATE.test(item)) problems.push(`${where}: ${JSON.stringify(item)} is not an ISO 8601 date`);
      } else if (typeof item === "number") {
        if (!property.range.some((r) => ["Number", "Integer", "Float"].includes(r))) problems.push(`${where}: a number where ${property.range} is expected`);
      } else if (typeof item === "boolean") {
        if (!property.range.includes("Boolean")) problems.push(`${where}: a boolean where ${property.range} is expected`);
      } else if (item && typeof item === "object") {
        const sub = lineage((item as any)["@type"]);
        if (!property.range.some((r) => sub.includes(r))) problems.push(`${where}: ${(item as any)["@type"]} where ${property.range} is expected`);
        problems.push(...validate(item as any, where));
      } else {
        problems.push(`${where}: unexpected value ${JSON.stringify(item)}`);
      }
    }
  }
  return problems;
}

type Head = {
  title: string;
  canonical: string[];
  ogUrl: string[];
  robots: string | null;
  meta: (name: string) => string[];
  jsonLd: any[];
  html: string;
};

function headOf(html: string): Head {
  const head = html.slice(0, html.indexOf("</head>"));
  const decode = (s: string) => s.replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
  const all = (re: RegExp) => [...head.matchAll(re)].map((m) => decode(m[1]));
  return {
    html,
    title: decode(head.match(/<title>([^<]*)<\/title>/)![1]),
    canonical: all(/<link rel="canonical" href="([^"]*)"/g),
    ogUrl: all(/<meta property="og:url" content="([^"]*)"/g),
    robots: all(/<meta name="robots" content="([^"]*)"/g)[0] ?? null,
    meta: (name) => all(new RegExp(`<meta name="${name}" content="([^"]*)"`, "g")),
    jsonLd: all(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g).flatMap((text) => [JSON.parse(text)].flat()),
  };
}

async function get(path: string): Promise<Head> {
  const res = await app.request(`http://localhost${path}`);
  expect(res.status, path).toBe(200);
  return headOf(await res.text());
}

const ORIGIN = "https://reportsthatmatter.org";

describe("registry carries what the head needs", () => {
  it.each(registry.map((r) => [r.id, r] as const))("%s", (_id, r) => {
    for (const field of ["common_name", "issued_by", "date_published", "repo"]) expect(r[field], field).toBeTruthy();
    expect(r.also_known_as?.length, "also_known_as").toBeGreaterThan(0);
    expect(r.date_published).toMatch(ISO_DATE);
    // The machine date must say what the display date says.
    const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    const shown = String(r.published_at).match(/^(?:(\d{1,2}) )?([A-Z][a-z]+) (\d{4})$/)!;
    const expected = [shown[3], String(months.indexOf(shown[2]) + 1).padStart(2, "0"), shown[1]?.padStart(2, "0")].filter(Boolean).join("-");
    expect(r.date_published).toBe(expected);
    if (r.license) expect(r.license.url).toMatch(/^https:\/\//);
  });
});

describe("JSON-LD is valid schema.org", () => {
  it("rejects what the validator is meant to catch", () => {
    expect(validate({ "@type": "Report", name: "x", datePublished: "22 July 2004" }).join()).toContain("ISO 8601");
    expect(validate({ "@type": "Report", name: "x", flavour: "y" }).join()).toContain("not a schema.org property");
    expect(validate({ "@type": "Report", author: { "@type": "BreadcrumbList" } }).join()).toContain("where");
    expect(validate({ "@type": "ListItem", datePublished: "2020-01-01" }).join()).toContain("not valid on ListItem");
  });

  it.each(registry.map((r) => [r.id, r] as const))("report and section markup for %s", (_id, r) => {
    const section = { title: "A section", slug: "a-section" };
    for (const text of [reportJsonLd(r as any, "d"), sectionJsonLd(r as any, section, "d")]) {
      const nodes = [JSON.parse(text)].flat();
      expect(nodes.flatMap((n) => validate(n))).toEqual([]);
    }
    const report = JSON.parse(reportJsonLd(r as any, "d"));
    expect(report["@type"]).toBe("Report");
    expect(report.author).toEqual({ "@type": "Organization", name: r.issued_by });
    expect(report.publisher.name).toBe("Reports that Matter");
    expect(report.datePublished).toBe(r.date_published);
    expect(report.isBasedOn.url).toBe(r.source_url);
    expect(report.archivedAt).toBe(`https://github.com/reportsthatmatter/${r.repo}`);
    if (r.common_name !== r.title) expect(report.alternateName).toContain(r.common_name);
    if (r.license) expect(report.license).toBe(r.license.url);
    else expect(report).not.toHaveProperty("license");
  });

  it("escapes anything that could close the script element", () => {
    const text = reportJsonLd({ id: "x", title: "</script><b>" }, "<!-- d");
    expect(text).not.toContain("<");
    expect(JSON.parse(text).name).toBe("</script><b>");
  });

  it("the site's own markup is valid", () => {
    expect([JSON.parse(siteJsonLd())].flat().flatMap((n) => validate(n))).toEqual([]);
  });
});

describe("citation_* tags", () => {
  const smith = registry.find((r) => r.id === "us-911-commission")!;
  const tags = Object.fromEntries(citationMeta(smith as any).map((t) => [t.name, t.content]));

  it("describe the report, its issuing body and its date in Scholar's format", () => {
    expect(tags.citation_title).toBe(smith.title);
    expect(tags.citation_author).toBe(smith.issued_by);
    expect(tags.citation_publication_date).toBe("2004/07/22");
    expect(tags.citation_fulltext_html_url).toBe(`${ORIGIN}/reports/us-911-commission/full`);
  });

  it("never claim a PDF we do not serve", () => {
    expect(Object.keys(tags)).not.toContain("citation_pdf_url");
  });
});

describe("titles", () => {
  it("lead with the common name", () => {
    for (const r of registry) {
      expect(reportTitle(r as any).startsWith(r.common_name), r.id).toBe(true);
      expect(reportTitle(r as any).length, r.id).toBeLessThanOrEqual(100);
    }
  });

  it("set all-caps headings in title case, for the title only, and leave the rest alone", () => {
    expect(displayHeading("COMMISSION STAFF")).toBe("Commission Staff");
    expect(displayHeading('"WE HAVE SOME PLANES"')).toBe('"We Have Some Planes"');
    expect(displayHeading("THE FOUNDATION OF THE NEW TERRORISM")).toBe("The Foundation of the New Terrorism");
    expect(displayHeading("UK INFLUENCE ON THE CPA")).toBe("UK Influence on the Cpa");
    expect(displayHeading("CASE STUDY OF MOODY'S AND STANDARD & POOR'S")).toBe("Case Study of Moody's and Standard & Poor's");
    expect(displayHeading("TIRC/CTR")).toBe("TIRC/CTR");
    expect(displayHeading("3.3 WING LEADING EDGE STRUCTURAL SUBSYSTEM")).toBe("3.3 Wing Leading Edge Structural Subsystem");
    expect(displayHeading("Already Fine, with NASA")).toBe("Already Fine, with NASA");
    expect(displayHeading("1.2 Improvising a Homeland Defense")).toBe("1.2 Improvising a Homeland Defense");
  });

  it("a section title is its heading, then the report's name", () => {
    expect(sectionTitle({ title: "Official", common_name: "9/11 Commission Report" }, { title: "COMMISSION STAFF" })).toBe("Commission Staff — 9/11 Commission Report");
  });
});

describe.each(registry.map((r) => [r.id, r] as const))("rendered head of %s", (id, r) => {
  const reportUrl = `${ORIGIN}/reports/${id}`;

  it("report page: canonical, title, JSON-LD, citation tags", async () => {
    const head = await get(`/reports/${id}`);
    expect(head.canonical).toEqual([reportUrl]);
    expect(head.ogUrl).toEqual([reportUrl]);
    expect(head.title.startsWith(r.common_name)).toBe(true);
    expect(head.robots).toBeNull();
    expect(head.jsonLd.flatMap((n) => validate(n))).toEqual([]);
    expect(head.jsonLd[0]["@type"]).toBe("Report");
    expect(head.meta("citation_title")).toEqual([r.title]);
    expect(head.meta("citation_author")).toEqual([r.issued_by]);
    expect(head.meta("citation_pdf_url")).toEqual([]);
  });

  it("report page with ?draft or a stray query still canonicalises to itself", async () => {
    expect((await get(`/reports/${id}?utm_source=x`)).canonical).toEqual([reportUrl]);
  });

  it("/full: its own title and canonical", async () => {
    const full = await get(`/reports/${id}/full`);
    const landing = await get(`/reports/${id}`);
    expect(full.canonical).toEqual([`${reportUrl}/full`]);
    expect(full.title).not.toBe(landing.title);
    expect(full.title.startsWith(r.common_name)).toBe(true);
    expect(full.meta("citation_fulltext_html_url")).toEqual([`${reportUrl}/full`]);
  });

  it("a section: canonical, breadcrumbs, part of the report; a ?p= link canonicalises to the bare section", async () => {
    const meta = JSON.parse(readFileSync(join(import.meta.dirname, `../assets/generated/reports/${id}/meta.json`), "utf8"));
    const slug = meta.sections[1].slug;
    const plain = await get(`/reports/${id}/${slug}`);
    expect(plain.canonical).toEqual([`${reportUrl}/${slug}`]);
    expect(plain.title.endsWith(` — ${r.common_name}`)).toBe(true);
    expect(plain.title).not.toContain("Reports that Matter");
    expect(plain.jsonLd.map((n) => n["@type"])).toEqual(["Report", "BreadcrumbList"]);
    expect(plain.jsonLd.flatMap((n) => validate(n))).toEqual([]);
    expect(plain.jsonLd[0].isPartOf.url).toBe(reportUrl);
    expect(plain.meta("citation_title")).toEqual([]);

    const paragraph = plain.html.match(/<p id="([a-z0-9-]+)"/)?.[1];
    expect(paragraph).toBeTruthy();
    const shared = await get(`/reports/${id}/${slug}?p=${paragraph}`);
    expect(shared.canonical).toEqual([`${reportUrl}/${slug}`]);
    expect(shared.jsonLd.flatMap((n) => validate(n))).toEqual([]);
  });

  it("a ?p= link on /full canonicalises to /full", async () => {
    const full = await get(`/reports/${id}/full`);
    const paragraph = full.html.match(/<p id="([a-z0-9-]+)"/)?.[1];
    expect((await get(`/reports/${id}/full?p=${paragraph}`)).canonical).toEqual([`${reportUrl}/full`]);
  });
});

describe("the other pages", () => {
  it.each([
    ["/", `${ORIGIN}/`],
    ["/reports", `${ORIGIN}/reports`],
    ["/about", `${ORIGIN}/about`],
    ["/press", `${ORIGIN}/press`],
    ["/changelog", `${ORIGIN}/changelog`],
    ["/highlights", `${ORIGIN}/highlights`],
    ["/search", `${ORIGIN}/search`],
  ])("%s has one canonical", async (path, canonical) => {
    const head = await get(path);
    expect(head.canonical).toEqual([canonical]);
    expect(head.ogUrl).toEqual([canonical]);
  });

  it("the home page says what the site is", async () => {
    const head = await get("/");
    expect(head.jsonLd.map((n) => n["@type"])).toEqual(["WebSite", "Organization"]);
    expect(head.jsonLd.flatMap((n) => validate(n))).toEqual([]);
  });

  it("search results are not indexed, the empty search page is", async () => {
    const results = await get("/search?q=planes");
    expect(results.robots).toBe("noindex");
    expect(results.canonical).toEqual([`${ORIGIN}/search`]);
    expect((await get("/search")).robots).toBeNull();
  });
});

describe("sitemap and robots", () => {
  it("list only canonical URLs: no /full, no processing notes, no query strings", async () => {
    const sitemap = await (await app.request("http://localhost/sitemap.xml")).text();
    const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    expect(locs.length).toBeGreaterThan(registry.length);
    for (const loc of locs) {
      expect(loc).not.toMatch(/\/full$|\/processing$|\?/);
      expect(loc.startsWith("http://localhost/")).toBe(true);
    }
    expect(new Set(locs).size).toBe(locs.length);
    for (const r of registry) expect(locs).toContain(`http://localhost/reports/${r.id}`);
  });

  it("robots.txt allows crawling and names the sitemap", async () => {
    const robots = await (await app.request("http://localhost/robots.txt")).text();
    expect(robots).toContain("User-agent: *\nAllow: /");
    expect(robots).toContain("Sitemap: http://localhost/sitemap.xml");
    expect(robots).not.toMatch(/Disallow:\s*\/\s*$/m);
  });
});
