/* Paragraph-id aliases and the record of every id ever published (reportsthatmatter-q8c).
 *
 *   pnpm aliases generate [<id>... | --all] [--old-ref origin/main] [--old <full.md>]
 *       Old text (the report's full.md at --old-ref, i.e. what is published) against the new text
 *       (the working tree's reports/<id>/full.md): writes reports/<id>/aliases.yaml and adds every id of
 *       both to reports/<id>/published-ids.txt. Idempotent; run after `pnpm ingest aggregate`
 *       on every re-ingest, then `pnpm prerender`.
 *   pnpm aliases seed [<id>... | --all] [--ref origin/main]
 *       Rebuilds both files from the git history of reports/<id>/full.md (every distinct version, oldest
 *       first, folded one step at a time into the working tree's text). For the first run and for backfill.
 *   pnpm aliases check
 *       Every recorded id is either in the current text, an alias of something that is, or named in
 *       `unmatched` (a loss somebody can read). Every alias lands on a current id. Every current id is
 *       recorded. Fails otherwise. Part of verify.sh; needs `pnpm prerender`.
 *
 * Files, per report, in this repo (not the report repo: aliases are derived from what was published,
 * which only this repo knows; a report repo's own aliases.yaml, as in us-911-commission#9, is not read):
 *   aliases.yaml       {aliases: {old: new}, sections: {old-slug: new-slug}, unmatched: [old]}
 *   published-ids.txt  one id per line, sorted
 * Matching is by text containment; see src/lib/alias-gen.ts.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse, stringify } from "yaml";
import { extractPassages } from "@rtm/ingest";
import { followAlias } from "../src/lib/aliases";
import { emptyAliases, fold, formatIds, idsOf, parseIds, render, type AliasFile, type Rendered } from "../src/lib/alias-gen";
import { assertFresh } from "./prerender-stamp.mjs";

const root = join(import.meta.dirname, "..");
const registry = parse(readFileSync(join(root, "reports/registry.yaml"), "utf8")) as { reports: { id: string; source_path: string }[] };
const [cmd, ...rest] = process.argv.slice(2);

const flag = (name: string) => {
  const i = rest.indexOf(name);
  return i >= 0 ? rest[i + 1] : undefined;
};
const VALUE_FLAGS = new Set(["--old-ref", "--old", "--ref"]);
const positional = rest.filter((a, i) => !a.startsWith("--") && !VALUE_FLAGS.has(rest[i - 1] ?? ""));
const ids = rest.includes("--all") || !positional.length ? registry.reports.map((r) => r.id) : positional;

const aliasesPath = (id: string) => join(root, `reports/${id}/aliases.yaml`);
const recordPath = (id: string) => join(root, `reports/${id}/published-ids.txt`);

function loadAliases(id: string): AliasFile {
  if (!existsSync(aliasesPath(id))) return emptyAliases();
  const y = parse(readFileSync(aliasesPath(id), "utf8")) ?? {};
  return { aliases: y.aliases ?? {}, sections: y.sections ?? {}, unmatched: y.unmatched ?? [] };
}
const loadRecord = (id: string) => (existsSync(recordPath(id)) ? parseIds(readFileSync(recordPath(id), "utf8")) : []);

const HEADER =
  "# Generated by `pnpm aliases generate` (reportsthatmatter-q8c); do not edit by hand.\n" +
  "# aliases: an id that used to be published -> the id that holds its text now. sections: likewise for section slugs.\n" +
  "# unmatched: ids whose text could not be found in the new text; a ?p= to one of these is a plain miss.\n";

function save(id: string, file: AliasFile, record: Iterable<string>) {
  const empty = !Object.keys(file.aliases).length && !Object.keys(file.sections).length && !file.unmatched.length;
  if (empty) {
    if (existsSync(aliasesPath(id))) writeFileSync(aliasesPath(id), HEADER + "aliases: {}\n");
  } else writeFileSync(aliasesPath(id), HEADER + stringify(file, { lineWidth: 0 }));
  writeFileSync(recordPath(id), formatIds(record));
}

const git = (...args: string[]) => execFileSync("git", args, { cwd: root, encoding: "utf8", maxBuffer: 1 << 29 });
const gitShow = (ref: string, path: string): string | null => {
  try {
    return git("show", `${ref}:${path}`);
  } catch {
    return null;
  }
};
const summary = (id: string, file: AliasFile, before: number, record: number) =>
  console.log(`  ${id}: ${Object.keys(file.aliases).length} alias(es) (${Object.keys(file.aliases).length - before} new), ${Object.keys(file.sections).length} section alias(es), ${file.unmatched.length} unmatched, ${record} id(s) recorded`);

function generate() {
  const ref = flag("--old-ref") ?? "origin/main";
  const oldPath = flag("--old");
  for (const id of ids) {
    const entry = registry.reports.find((r) => r.id === id);
    if (!entry) throw new Error(`no such report: ${id}`);
    const next = render(readFileSync(join(root, entry.source_path), "utf8"));
    const oldMd = oldPath ? readFileSync(oldPath, "utf8") : gitShow(ref, entry.source_path);
    const prev = loadAliases(id);
    const record = new Set([...loadRecord(id), ...idsOf(next)]);
    let file: AliasFile;
    if (oldMd === null) file = fold(prev, next, next);
    else {
      const old = render(oldMd);
      for (const x of idsOf(old)) record.add(x);
      file = fold(prev, old, next);
    }
    save(id, file, record);
    summary(id, file, Object.keys(prev.aliases).length, record.size);
  }
}

function seed() {
  const ref = flag("--ref") ?? "origin/main";
  for (const id of ids) {
    const entry = registry.reports.find((r) => r.id === id);
    if (!entry) throw new Error(`no such report: ${id}`);
    const commits = git("log", "--reverse", "--format=%H", ref, "--", entry.source_path).split("\n").filter(Boolean);
    const seen = new Set<string>();
    const versions: Rendered[] = [];
    for (const c of commits) {
      let blob: string;
      try {
        blob = git("rev-parse", `${c}:${entry.source_path}`).trim();
      } catch {
        continue;
      }
      if (seen.has(blob)) continue;
      seen.add(blob);
      versions.push(render(git("show", blob)));
    }
    versions.push(render(readFileSync(join(root, entry.source_path), "utf8")));
    const record = new Set<string>();
    let file = emptyAliases();
    for (let i = 0; i < versions.length; i++) {
      for (const x of idsOf(versions[i])) record.add(x);
      if (i > 0) file = fold(file, versions[i - 1], versions[i]);
    }
    save(id, file, record);
    summary(id, file, 0, record.size);
  }
}

function check() {
  assertFresh("pnpm aliases check");
  let failed = 0;
  for (const id of ids) {
    const dir = join(root, `assets/generated/reports/${id}`);
    const meta = JSON.parse(readFileSync(join(dir, "meta.json"), "utf8"));
    const live = new Set<string>();
    for (const s of meta.sections) for (const p of extractPassages(readFileSync(join(dir, `fragments/${s.slug}.html`), "utf8"))) live.add(p.paragraphId);
    const { aliases, sections, unmatched } = loadAliases(id);
    const problems: string[] = [];
    if (!existsSync(recordPath(id))) problems.push("no published-ids.txt (run pnpm aliases seed)");
    const record = new Set(loadRecord(id));
    const missing = [...live].filter((x) => !record.has(x));
    if (missing.length) problems.push(`${missing.length} current id(s) not recorded, e.g. ${missing.slice(0, 3).join(", ")} (run pnpm aliases generate ${id})`);
    const lostIds = [...record].filter((x) => !live.has(x) && !followAlias(aliases, x, (y) => live.has(y)) && !unmatched.includes(x));
    if (lostIds.length) problems.push(`${lostIds.length} published id(s) resolve nowhere and are not in unmatched, e.g. ${lostIds.slice(0, 3).join(", ")}`);
    const dead = Object.entries(aliases).filter(([, to]) => !live.has(to));
    if (dead.length) problems.push(`${dead.length} alias(es) point at an id that is not current, e.g. ${dead[0][0]} -> ${dead[0][1]}`);
    const shadowed = Object.keys(aliases).filter((k) => live.has(k));
    if (shadowed.length) problems.push(`${shadowed.length} alias key(s) are current ids, e.g. ${shadowed[0]}`);
    const slugs = new Set(meta.sections.map((s: { slug: string }) => s.slug));
    const deadSections = Object.entries(sections).filter(([, to]) => !slugs.has(to));
    if (deadSections.length) problems.push(`${deadSections.length} section alias(es) point at a missing section, e.g. ${deadSections[0][0]}`);
    const served = meta.paragraphAliases ?? {};
    const unserved = Object.keys(aliases).filter((k) => served[k] !== aliases[k]);
    if (unserved.length) problems.push(`${unserved.length} alias(es) not in the pre-rendered meta.json (run pnpm prerender)`);
    if (problems.length) {
      failed++;
      console.error(`  \x1b[31m✗\x1b[0m ${id}`);
      for (const p of problems) console.error(`      ${p}`);
    } else console.log(`  \x1b[32m✓\x1b[0m ${id}: ${record.size} recorded id(s), ${Object.keys(aliases).length} alias(es), ${unmatched.length} unmatched`);
  }
  process.exit(failed ? 1 : 0);
}

if (cmd === "generate") generate();
else if (cmd === "seed") seed();
else if (cmd === "check") check();
else {
  console.error("usage: pnpm aliases generate|seed [<id>... | --all] | check");
  process.exit(2);
}
