/* Bundles content/posts/*.md for the Worker (reportsthatmatter-jedz).
 *
 *   pnpm blog           validate every post and write src/generated/posts-bundle.ts
 *   pnpm blog --check   fail if that file is out of date (tests/blog-bundle.test.ts)
 *
 * The Worker cannot read the directory at run time, so the raw files ship as
 * one generated module, committed like src/generated/editorial.ts. Run this
 * after adding or editing a post.
 */
import "./lib/help.mjs";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parsePosts } from "../src/lib/blog.ts";

const root = join(import.meta.dirname, "..");
const dir = join(root, "content/posts");
const out = join(root, "src/generated/posts-bundle.ts");

export function buildBundle() {
  const files = {};
  for (const name of readdirSync(dir).sort()) {
    if (name.endsWith(".md")) files[name.slice(0, -3)] = readFileSync(join(dir, name), "utf8");
  }
  parsePosts(files); // throws, naming the file, on a malformed post
  return (
    "/* Generated by scripts/blog.mjs from content/posts/*.md — do not edit. */\n" +
    `export const POST_FILES: Readonly<Record<string, string>> = ${JSON.stringify(files, null, 2)};\n`
  );
}

if (process.argv[1] === import.meta.filename) {
  const next = buildBundle();
  if (process.argv.includes("--check")) {
    if (!existsSync(out) || readFileSync(out, "utf8") !== next) {
      console.error("src/generated/posts-bundle.ts is out of date. Run: pnpm blog");
      process.exit(1);
    }
  } else {
    writeFileSync(out, next);
    console.log(`Bundled ${Object.keys(JSON.parse(next.slice(next.indexOf("{"), next.lastIndexOf("}") + 1))).length} post(s).`);
  }
}
