/* Checks our editorial layer against the reports and builds what the Worker
 * reads (reportsthatmatter-g0w.1).
 *
 *   pnpm editorial
 *
 * For every `editorial/<report-id>.yaml`: each excerpt's quote must appear
 * verbatim in its paragraph (or in the block quotations that paragraph
 * introduces), and every cited paragraph id must exist. Checked against the
 * pre-rendered body in assets/generated/, so run `pnpm prerender` first — the
 * same ids the reader is served, not a second rendering that could disagree.
 *
 * Writes src/generated/editorial.ts, drafts included: only the template
 * decides what a reader sees, so a draft can be previewed with `?draft` on
 * the contents page before it is approved. Exits 1 on any problem, listing
 * all of them.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";
import { resolveEditorial } from "../src/lib/editorial.ts";

const root = join(import.meta.dirname, "..");
const dir = join(root, "editorial");
const registry = parse(readFileSync(join(root, "reports/registry.yaml"), "utf8"));
const known = new Set(registry.reports.map((report) => report.id));

const problems = [];
const resolved = {};

const files = existsSync(dir) ? readdirSync(dir).filter((name) => name.endsWith(".yaml")).sort() : [];

for (const name of files) {
  const source = parse(readFileSync(join(dir, name), "utf8"));
  const expected = name.replace(/\.yaml$/, "");

  if (source.report !== expected) {
    problems.push(`${name}: report is "${source.report}", but the file is named for "${expected}"`);
    continue;
  }
  if (!known.has(source.report)) {
    problems.push(`${name}: no report "${source.report}" in reports/registry.yaml`);
    continue;
  }

  const bodyPath = join(root, `assets/generated/reports/${source.report}/full-body.html`);
  if (!existsSync(bodyPath)) {
    problems.push(`${name}: ${bodyPath} is missing — run pnpm prerender first`);
    continue;
  }

  const result = resolveEditorial(source, readFileSync(bodyPath, "utf8"));
  problems.push(...result.problems);
  resolved[source.report] = result.editorial;

  console.log(
    `  ${result.problems.length ? "✗" : "✓"} ${source.report} (${source.status}) — ` +
      `${result.editorial.findings.length} findings, ${result.editorial.excerpts.length} excerpts`
  );
}

writeFileSync(
  join(root, "src/generated/editorial.ts"),
  `/* Generated by scripts/editorial.mjs from editorial/*.yaml — do not edit. */
import type { Editorial } from "../lib/editorial";

export const EDITORIAL: Readonly<Record<string, Editorial>> = ${JSON.stringify(resolved, null, 2)};
`
);

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`);
  for (const problem of problems) console.error(`  - ${problem}`);
  process.exit(1);
}

console.log(`\nChecked ${files.length} editorial file(s); wrote src/generated/editorial.ts`);
