"""Score the referee pilot against adjudicated labels (38s.8).

Every held-out row in the pilot where any decider (pipeline, R2, tree, referee)
disagreed with the reference was read against the PDF (pdftotext -layout around
the break, as printed by referee.context) and given a verdict: J (same block),
S (new block) or X (cannot be judged from the page: the dataset paired the
wrong lines, usually a footnote or the other column of a two-column page). Rows
where every decider agreed with the reference keep the reference label.
"""
import os
import pandas as pd

HERE = os.path.dirname(__file__)
# row index in results/referee-sonnet-rows.jsonl -> verdict
VERDICT = {
    0: "J", 1: "S", 2: "J", 3: "X", 4: "J", 5: "J", 7: "J", 8: "J", 9: "S", 11: "J", 12: "J", 13: "J", 15: "S", 16: "J", 17: "S", 18: "J", 19: "S", 20: "S",
    23: "J", 24: "J", 27: "J", 28: "S", 30: "J", 31: "S", 32: "J", 34: "S", 35: "S", 36: "S", 37: "J", 41: "S", 42: "S", 50: "S", 54: "S", 59: "S", 60: "S",
    61: "S", 62: "J", 63: "S", 64: "J", 66: "X", 67: "X", 69: "S", 74: "S", 76: "S", 89: "J", 92: "J", 95: "J", 96: "J", 100: "J", 103: "X", 104: "J",
    108: "S", 109: "J", 110: "J", 115: "X", 119: "J", 120: "J", 126: "J", 127: "J", 129: "X", 131: "J", 135: "J", 136: "J", 138: "X", 148: "J", 150: "J",
    152: "X", 155: "S", 160: "S", 164: "X", 166: "X", 167: "X", 171: "J", 179: "J", 183: "J", 187: "J", 188: "S", 190: "J", 195: "S",
}


def main(model="sonnet"):
    r = pd.read_json(os.path.join(HERE, "results", f"referee-{model}-rows.jsonl"), lines=True)
    r["ref_join"] = ~r.ref_boundary
    dis = (r.pipeline_join != r.ref_join) | (r.r2_join != r.ref_join) | (r.tree_join != r.ref_join) | (r.referee_join != r.ref_join)
    missing = set(r[dis].index) - set(VERDICT)
    assert not missing, f"unadjudicated rows: {sorted(missing)}"
    r["truth"] = r.ref_join.map({True: "J", False: "S"})
    for i, v in VERDICT.items():
        r.loc[i, "truth"] = v
    r["ref_wrong"] = (r.truth != "X") & (r.truth != r.ref_join.map({True: "J", False: "S"}))
    k = r[r.truth != "X"].copy()
    k["tj"] = k.truth == "J"
    out = ["# Referee pilot against adjudicated labels\n", f"Generated by `adjudicate.py`. {dis.sum()} of {len(r)} pilot rows had a decider disagreeing with the reference and were read against the PDF: the reference was wrong on {int(r.ref_wrong.sum())}, and {int((r.truth == 'X').sum())} could not be judged (the dataset paired the wrong lines: a footnote, or the other column) and are dropped.\n"]
    out.append("| sample | report | n | reference | pipeline | tree | R2 | referee |\n|---|---|---:|---:|---:|---:|---:|---:|")
    groups = list(k.groupby(["sample", "report"])) + [((s, "all"), g) for s, g in k.groupby("sample")] + [(("both", "all"), k)]
    for (s, rep), g in groups:
        f = lambda c: (g[c] == g.tj).mean()
        out.append(f"| {s} | {rep} | {len(g)} | {f('ref_join'):.1%} | {f('pipeline_join'):.1%} | {f('tree_join'):.1%} | {f('r2_join'):.1%} | {f('referee_join'):.1%} |")
    # referee as a tie-breaker: use R2 unless the row is ambiguous, then the referee
    k["hybrid"] = k.r2_join.where(k["sample"] != "ambiguous", k.referee_join)
    a = k[k["sample"] == "ambiguous"]
    out.append(f"\nOn the ambiguous rows the referee is right {(a.referee_join == a.tj).mean():.1%} of the time, R2 {(a.r2_join == a.tj).mean():.1%}, the pipeline {(a.pipeline_join == a.tj).mean():.1%}.")
    out.append(f"\nReading the referee's remaining errors: {', '.join(f'{rep} {n}' for rep, n in k[k.referee_join != k.tj].report.value_counts().items())}.")
    md = "\n".join(out) + "\n"
    open(os.path.join(HERE, "results", f"referee-{model}-adjudicated.md"), "w").write(md)
    r.to_json(os.path.join(HERE, "results", f"referee-{model}-adjudicated.jsonl"), orient="records", lines=True)
    print(md)
    return k


if __name__ == "__main__":
    k = main()
    for _, x in k[k.referee_join != k.tj].iterrows():
        print(x.name, x.report, x['sample'], "truth", x.truth, "| ", x.prev_text[-40:], "||", x.next_text[:40])
