"""Block type, quotation vs. prose (38s.8): pipeline vs. a learned tree.

Rows: decision=block where the reference type is paragraph or quote and ours is
paragraph or quote. Features are the block's text shape and its first line's
layout, plus document-relative font features (is this the document's body
font? how much of the document is set in it?) so that a rule learnt on one
publisher can transfer. Writes results/blocktype.md and results/blocktype-tree.txt.
"""
import os, warnings
import numpy as np, pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text
from load import load, DEV, HOLDOUT

warnings.filterwarnings("ignore")
OUT = os.path.join(os.path.dirname(__file__), "results")
TYPES = {"paragraph", "quote"}


def frame(reports):
    d = load(reports, "block")
    d = d[d.ref_type.isin(TYPES) & d.ours_type.isin(TYPES)].copy()
    # document-relative font: the font carrying the most words of this report's blocks
    w = d.groupby(["report", "line_font"]).text_words.sum().reset_index()
    modal = w.sort_values("text_words").groupby("report").tail(1).set_index("report").line_font
    share = w.assign(s=w.text_words / w.groupby("report").text_words.transform("sum")).set_index(["report", "line_font"]).s
    d["font_is_body"] = d.line_font == d.report.map(modal)
    d["font_share"] = [share.get((r, f), 0) for r, f in zip(d.report, d.line_font)]
    em = d.line_size.where(d.line_size > 0, 10)
    d["indent_em"] = d.line_indent / em
    d["right_gap_em"] = d.line_right_gap / em
    d["prev_is_quote"] = d.prev_type == "quote"
    d["prev_is_para"] = d.prev_type == "paragraph"
    d["ref_quote"] = d.ref_type == "quote"
    d["ours_quote"] = d.ours_type == "quote"
    return d


NUM = ["text_words", "text_caps_ratio", "line_size_rel", "line_width_rel", "indent_em", "right_gap_em", "font_share", "markers"]
BOOL = ["font_is_body", "text_opens_quote", "text_closes_quote", "text_starts_label", "text_ends_sentence", "prev_ends_sentence", "line_italic", "line_bold", "prev_is_quote", "prev_is_para", "after_page_break"]


def X(d, ours=False):
    cols = NUM + BOOL + (["ours_quote"] if ours else [])
    x = d[cols].copy()
    for c in BOOL + (["ours_quote"] if ours else []):
        x[c] = x[c].fillna(False).astype(int)
    return x.astype(float).fillna(-999)


def w(d):
    return d.report.map(1 / d.report.value_counts()).values


def main():
    dev, hold = frame(DEV), frame(HOLDOUT)
    md = ["# Block type (quotation vs. prose): results\n", "Generated by `blocktype.py`. Accuracy over blocks both we and the reference type as paragraph or quote.\n"]
    md.append("| report | blocks | ref quotes | pipeline | tree, trained on the other dev reports | tree + our type |\n|---|---:|---:|---:|---:|---:|")
    for r in DEV:
        tr, te = dev[dev.report != r], dev[dev.report == r]
        m = DecisionTreeClassifier(max_depth=4, min_samples_leaf=10, random_state=0).fit(X(tr), tr.ref_quote, sample_weight=w(tr))
        m2 = DecisionTreeClassifier(max_depth=4, min_samples_leaf=10, random_state=0).fit(X(tr, True), tr.ref_quote, sample_weight=w(tr))
        md.append(f"| {r} (dev, leave-one-out) | {len(te)} | {int(te.ref_quote.sum())} | {(te.ours_quote == te.ref_quote).mean():.1%} | {(m.predict(X(te)) == te.ref_quote).mean():.1%} | {(m2.predict(X(te, True)) == te.ref_quote).mean():.1%} |")
    m = DecisionTreeClassifier(max_depth=4, min_samples_leaf=10, random_state=0).fit(X(dev), dev.ref_quote, sample_weight=w(dev))
    m2 = DecisionTreeClassifier(max_depth=4, min_samples_leaf=10, random_state=0).fit(X(dev, True), dev.ref_quote, sample_weight=w(dev))
    for r in HOLDOUT:
        te = hold[hold.report == r]
        if len(te) == 0:
            continue
        md.append(f"| {r} (held-out) | {len(te)} | {int(te.ref_quote.sum())} | {(te.ours_quote == te.ref_quote).mean():.1%} | {(m.predict(X(te)) == te.ref_quote).mean():.1%} | {(m2.predict(X(te, True)) == te.ref_quote).mean():.1%} |")
    names = list(X(dev).columns)
    open(os.path.join(OUT, "blocktype-tree.txt"), "w").write("Depth-4 tree, quote (True) vs paragraph, trained on the development reports.\n\n" + export_text(m, feature_names=names, show_weights=True))
    imp = sorted(zip(m.feature_importances_, names), reverse=True)
    md.append("\nFeature importance: " + ", ".join(f"{n} {v:.2f}" for v, n in imp if v > 0.01) + ".\n")
    # how separable is Saville by font alone
    s = dev[dev.report == "uk-saville-inquiry"]
    md.append(f"Saville by font alone (not the body font → quote): {((~s.font_is_body) == s.ref_quote).mean():.1%}; pipeline {(s.ours_quote == s.ref_quote).mean():.1%}.\n")
    open(os.path.join(OUT, "blocktype.md"), "w").write("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()


def within():
    """Ceiling: a tree trained on half a report's pages (odd) and tested on the other half (even)."""
    rows = []
    for r in DEV + HOLDOUT:
        d = frame([r])
        if d.ref_quote.sum() < 20:
            continue
        tr, te = d[d.page % 2 == 1], d[d.page % 2 == 0]
        m = DecisionTreeClassifier(max_depth=3, min_samples_leaf=10, random_state=0).fit(X(tr), tr.ref_quote)
        rows.append(f"| {r} | {len(te)} | {(te.ours_quote == te.ref_quote).mean():.1%} | {(m.predict(X(te)) == te.ref_quote).mean():.1%} | " + export_text(m, feature_names=list(X(tr).columns), max_depth=1).splitlines()[0].strip("|- ") + " |")
    md = "\n## Within one report (train on odd pages, test on even)\n\n| report | test blocks | pipeline | tree | first split |\n|---|---:|---:|---:|---|\n" + "\n".join(rows) + "\n"
    open(os.path.join(OUT, "blocktype.md"), "a").write(md)
    print(md)


if __name__ == "__main__":
    within()
