"""Cluster the pipeline's wrong page-break decisions (38s.8). Writes results/pagebreak-clusters.md.

Clusters (first match wins):
  artefact: reference starts a block in lower case after an unfinished one (a split the
            reference inherited from its own page break), or the next line is a bullet the
            reference keeps inside the paragraph (Chilcot tags)
  wrong join: the reference splits, we joined
  lower, quote/list: a lower-case continuation we split where our block is a quote or list
            (mergeAcrossPages joins only paragraph+paragraph, and list+paragraph)
  lower, paragraph: a lower-case continuation we split although both halves are paragraphs:
            something stood between them in our blocks (footnote text left in the body,
            a caption, a sidebar, furniture)
  capital after unfinished: next line opens on a capital, the previous line stops mid-sentence
  digit/bracket/quote: next line opens on a digit, bracket or quotation mark
  after finished sentence: the page ends a sentence and the paragraph carries on
"""
import os
import pandas as pd
from features import boundary_frame
from load import DEV, HOLDOUT

OUT = os.path.join(os.path.dirname(__file__), "results")


def cluster(x):
    if x.ref_boundary and x.next_first == "lower" and not x.prev_ends_sentence:
        return "artefact"
    if not x.ref_boundary and str(x.next_text).startswith("•"):
        return "artefact"
    if x.ref_boundary:
        return "wrong join"
    if x.next_first == "lower" or str(x.next_text)[:1] in ",;":
        return "lower, quote/list" if x.ours_next_type in ("quote", "list") else "lower, paragraph"
    if x.prev_ends_sentence:
        return "after finished sentence"
    if x.next_first == "upper":
        return "capital after unfinished"
    return "digit/bracket/quote"


def main():
    d = boundary_frame(DEV + HOLDOUT)
    pb = d[d.crosses_page & ~d.correct].copy()
    pb["cluster"] = pb.apply(cluster, axis=1)
    t = pd.crosstab(pb.cluster, pb.report)
    t = t[[r for r in DEV + HOLDOUT if r in t.columns]]
    t["all"] = t.sum(axis=1)
    t = t.sort_values("all", ascending=False)
    n = d[d.crosses_page].groupby("report").size()
    md = "# Pipeline's wrong page-break decisions, clustered\n\nGenerated by `errors.py`. Counts of wrong decisions per cluster; the last row is the number of page-break line breaks scored.\n\n"
    md += "| cluster | " + " | ".join(t.columns) + " |\n|---|" + "---:|" * len(t.columns) + "\n"
    for c, row in t.iterrows():
        md += f"| {c} | " + " | ".join(str(v) for v in row.values) + " |\n"
    md += "| page breaks scored | " + " | ".join(str(n.get(r, n.sum())) if r != "all" else str(n.sum()) for r in t.columns) + " |\n"
    open(os.path.join(OUT, "pagebreak-clusters.md"), "w").write(md)
    print(md)


if __name__ == "__main__":
    main()
