"""Heading vs. body (38s.8): pipeline vs. a learned tree, on blocks of 25 words or fewer.

Writes results/heading.md and results/heading-tree.txt.
"""
import os, warnings
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text
from load import load, DEV, HOLDOUT

warnings.filterwarnings("ignore")
OUT = os.path.join(os.path.dirname(__file__), "results")


def frame(reports):
    d = load(reports, "heading")
    d = d[d.ref_heading.notna()].copy()
    full = load(reports, "block")  # body font from all blocks, not just short ones
    w = full.groupby(["report", "line_font"]).text_words.sum().reset_index()
    modal = w.sort_values("text_words").groupby("report").tail(1).set_index("report").line_font
    d["font_is_body"] = d.line_font == d.report.map(modal)
    d["color_is_black"] = d.line_color.isin(["#000000", None])
    em = d.line_size.where(d.line_size > 0, 10)
    d["indent_em"] = d.line_indent / em
    d["ref_h"] = d.ref_heading.astype(bool)
    d["ours_h"] = d.ours_heading.astype(bool)
    return d


NUM = ["text_words", "text_caps_ratio", "line_size_rel", "line_width_rel", "indent_em", "markers"]
BOOL = ["font_is_body", "color_is_black", "line_bold", "line_italic", "text_ends_sentence", "text_starts_label", "prev_ends_sentence", "after_page_break"]


def X(d):
    x = d[NUM + BOOL].copy()
    for c in BOOL:
        x[c] = x[c].fillna(False).astype(int)
    return x.astype(float).fillna(-999)


def w(d):
    return d.report.map(1 / d.report.value_counts()).values


def main():
    dev, hold = frame(DEV), frame(HOLDOUT)
    mk = lambda: DecisionTreeClassifier(max_depth=4, min_samples_leaf=10, random_state=0)
    md = ["# Heading vs. body: results\n", "Generated by `heading.py`. Blocks of ours with 25 words or fewer (and every heading of ours); label: is it a heading in the reference. Headings fused into a paragraph are not in these rows.\n",
          "| report | rows | ref headings | pipeline | tree, trained on other dev reports |\n|---|---:|---:|---:|---:|"]
    for r in DEV:
        tr, te = dev[dev.report != r], dev[dev.report == r]
        m = mk().fit(X(tr), tr.ref_h, sample_weight=w(tr))
        md.append(f"| {r} (dev, leave-one-out) | {len(te)} | {int(te.ref_h.sum())} | {(te.ours_h == te.ref_h).mean():.1%} | {(m.predict(X(te)) == te.ref_h).mean():.1%} |")
    m = mk().fit(X(dev), dev.ref_h, sample_weight=w(dev))
    for r in HOLDOUT:
        te = hold[hold.report == r]
        md.append(f"| {r} (held-out) | {len(te)} | {int(te.ref_h.sum())} | {(te.ours_h == te.ref_h).mean():.1%} | {(m.predict(X(te)) == te.ref_h).mean():.1%} |")
    names = list(X(dev).columns)
    open(os.path.join(OUT, "heading-tree.txt"), "w").write("Depth-4 tree, heading (True) vs body, trained on the development reports.\n\n" + export_text(m, feature_names=names, show_weights=True))
    imp = sorted(zip(m.feature_importances_, names), reverse=True)
    md.append("\nFeature importance: " + ", ".join(f"{n} {v:.2f}" for v, n in imp if v > 0.01) + ".\n")
    open(os.path.join(OUT, "heading.md"), "w").write("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
