"""Page-break join decision (38s.8): pipeline vs. hand rules vs. learned models.

Trains on the development reports only (leave-one-report-out for model
choice), then scores once on the held-out reports. Writes
results/pagebreak.md and results/pagebreak-tree.txt, and the held-out rows the
tree is unsure of (results/ambiguous-holdout.jsonl) for the referee pilot.

    python pagebreak.py            # needs score-out/ from `pnpm score --all` and `--all --holdout`
"""
import json, os, warnings
import numpy as np, pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from features import boundary_frame, X, NUMERIC, BOOL
from load import DEV, HOLDOUT

warnings.filterwarnings("ignore")
OUT = os.path.join(os.path.dirname(__file__), "results")
os.makedirs(OUT, exist_ok=True)


def hand_rules(pb):
    """The candidate rules, as boolean 'join' Series."""
    flush = pb.next_first_indent_em.abs() < 0.6          # no first-line indent: next2 starts at the same left
    lower = (pb.next_first == "lower") | pb.next_text.str.match(r"^[,;]")
    nolabel = ~pb.next_starts_label                       # "57.", "(b)", "9.88"
    samefont = ~pb.font_change & (pb.size_change.abs() < 0.5)
    unfinished = ~pb.prev_ends_sentence
    justified_full = (pb.page_ragged_em < 0.5) & (pb.prev_right_gap_em.abs() < 0.5)
    r1 = unfinished & (flush | lower) & nolabel & samefont
    r2 = r1 | (pb.prev_ends_sentence & flush & nolabel & samefont & justified_full & (pb.next_words > 4))
    return {
        "pipeline": ~pb.ours_boundary,
        "R0 lower-case only (today's core rule, all block types)": lower & unfinished,
        "R1 unfinished & (flush or lower) & no label & same font": r1,
        "R2 R1, or finished & flush & full justified last line": r2,
    }


def weights(d):
    return d.report.map(1 / d.report.value_counts()).values


def make_tree(depth=4, leaf=5):
    return DecisionTreeClassifier(max_depth=depth, min_samples_leaf=leaf, random_state=0)


def Xlr(d):
    x = X(d, fill=0).clip(-20, 20)
    return x


def make_lr():
    return make_pipeline(StandardScaler(), LogisticRegression(C=0.1, max_iter=5000))


def acc(pred_join, d):
    return pd.Series(np.asarray(pred_join) == (~d.ref_boundary).values).groupby(d.report.values).mean()


def table(rows, reports):
    head = "| decider | " + " | ".join(r for r in reports) + " | mean |\n|---|" + "---:|" * (len(reports) + 1) + "\n"
    body = ""
    for name, a in rows:
        vals = [a.get(r, np.nan) for r in reports]
        body += f"| {name} | " + " | ".join(f"{v:.1%}" for v in vals) + f" | {np.nanmean(vals):.1%} |\n"
    return head + body


def main():
    dev = boundary_frame(DEV)
    hold = boundary_frame(HOLDOUT)
    pdev, phold = dev[dev.crosses_page].copy(), hold[hold.crosses_page].copy()
    md = ["# Page-break join decision: results\n", "Generated by `pagebreak.py`. Accuracy over page-break line breaks the reference covers (next block prose, quote, list, heading or contents).\n"]
    md.append(f"Rows: development {len(pdev)} ({', '.join(f'{r} {n}' for r, n in pdev.report.value_counts().items())}); held-out {len(phold)} ({', '.join(f'{r} {n}' for r, n in phold.report.value_counts().items())}).\n")

    # 1. leave-one-report-out on dev
    loro = {"tree (depth 4)": {}, "tree (depth 3)": {}, "logistic regression": {}}
    for r in DEV:
        tr, te = pdev[pdev.report != r], pdev[pdev.report == r]
        for name, depth in [("tree (depth 4)", 4), ("tree (depth 3)", 3)]:
            m = make_tree(depth).fit(X(tr), ~tr.ref_boundary, sample_weight=weights(tr))
            loro[name][r] = (m.predict(X(te)) == ~te.ref_boundary).mean()
        m = make_lr().fit(Xlr(tr), ~tr.ref_boundary, logisticregression__sample_weight=weights(tr))
        loro["logistic regression"][r] = (m.predict(Xlr(te)) == ~te.ref_boundary).mean()
    rows = [(k, acc(v, pdev).to_dict()) for k, v in hand_rules(pdev).items()]
    rows += [(f"{k}, trained on the other two", v) for k, v in loro.items()]
    md.append("## Development set\n\nHand rules were written after reading these reports' errors, so their dev numbers are in-sample; the learned models are scored leave-one-report-out (trained on the other two development reports).\n")
    md.append(table(rows, DEV))

    # 2. final models on all dev, scored once on hold-out
    tree = make_tree(4).fit(X(pdev), ~pdev.ref_boundary, sample_weight=weights(pdev))
    tree3 = make_tree(3).fit(X(pdev), ~pdev.ref_boundary, sample_weight=weights(pdev))
    lr = make_lr().fit(Xlr(pdev), ~pdev.ref_boundary, logisticregression__sample_weight=weights(pdev))
    rows = [(k, acc(v, phold).to_dict()) for k, v in hand_rules(phold).items()]
    rows.append(("tree (depth 4), trained on dev", acc(pd.Series(tree.predict(X(phold)), index=phold.index), phold).to_dict()))
    rows.append(("tree (depth 3), trained on dev", acc(pd.Series(tree3.predict(X(phold)), index=phold.index), phold).to_dict()))
    rows.append(("logistic regression, trained on dev", acc(pd.Series(lr.predict(Xlr(phold)), index=phold.index), phold).to_dict()))
    md.append("\n## Held-out set (scored once, after the deciders were fixed)\n")
    md.append(table(rows, HOLDOUT))

    # clean-label variant: drop rows whose reference starts a block in lower case after an unfinished one
    sus = phold.ref_boundary & (phold.next_first == "lower") & ~phold.prev_ends_sentence
    ph2 = phold[~sus]
    rows = [(k, acc(v, ph2).to_dict()) for k, v in hand_rules(ph2).items()]
    rows.append(("tree (depth 4), trained on dev", acc(pd.Series(tree.predict(X(ph2)), index=ph2.index), ph2).to_dict()))
    md.append(f"\nThe same, without the {int(sus.sum())} held-out rows whose reference starts a block in lower case after an unfinished one (reference artefacts, §2 of the design doc):\n")
    md.append(table(rows, HOLDOUT))

    # 3. what replacing only the page-break decisions does to all line breaks
    md.append("\n## Effect on all line breaks (page-break decisions replaced, in-page decisions kept)\n")
    allrows = []
    for name, d in [("dev", dev), ("held-out", hold)]:
        for rule in ["R1 unfinished & (flush or lower) & no label & same font", "R2 R1, or finished & flush & full justified last line"]:
            pbx = d[d.crosses_page]
            j = hand_rules(pbx)[rule]
            new = d.correct.copy()
            new.loc[pbx.index] = j.values == (~pbx.ref_boundary).values
            for r in d.report.unique():
                m = d.report == r
                allrows.append((name, r, rule[:2], d.correct[m].mean(), new[m].mean()))
    md.append("| set | report | rule | pipeline | with rule |\n|---|---|---|---:|---:|\n" + "".join(f"| {a} | {b} | {c} | {x:.2%} | {y:.2%} |\n" for a, b, c, x, y in allrows))

    # 4. tree text and feature importance
    names = list(X(pdev).columns)
    txt = export_text(tree3, feature_names=names, show_weights=True)
    open(os.path.join(OUT, "pagebreak-tree.txt"), "w").write("Depth-3 tree, trained on the three development reports (equal weight per report). class True = join.\n\n" + txt + "\n\nDepth-4 tree:\n\n" + export_text(tree, feature_names=names, show_weights=True))
    imp = sorted(zip(tree.feature_importances_, names), reverse=True)[:10]
    md.append("\n## Depth-4 tree: feature importance\n\n" + "".join(f"- {n}: {v:.3f}\n" for v, n in imp if v > 0))
    md.append("\nThe tree itself: `results/pagebreak-tree.txt`.\n")

    # 5. ambiguous held-out rows for the referee
    p = tree.predict_proba(X(phold))[:, 1]
    phold["tree_p_join"] = p
    phold["tree_join"] = p >= 0.5
    phold["r2_join"] = hand_rules(phold)["R2 R1, or finished & flush & full justified last line"].values
    amb = phold[(p > 0.1) & (p < 0.9) | (phold.tree_join != phold.r2_join)]
    keep = ["report", "page", "prev_page", "next_page", "ref_boundary", "ours_boundary", "ref_prev_type", "ref_next_type", "ours_next_type", "tree_p_join", "tree_join", "r2_join",
            "prev_text", "next_text", "prev_ends_sentence", "next_first_indent_em", "prev_indent_em", "next_indent_em", "next2_indent_em", "skipped_lines", "font_change", "prev_right_gap_em", "page_ragged_em"]
    amb[keep].to_json(os.path.join(OUT, "ambiguous-holdout.jsonl"), orient="records", lines=True)
    phold[keep].to_json(os.path.join(OUT, "holdout-pagebreaks.jsonl"), orient="records", lines=True)
    md.append(f"\n## Ambiguous rows\n\nHeld-out page breaks where the depth-4 tree's leaf is impure (0.1 < p(join) < 0.9) or the tree and R2 disagree: {len(amb)} of {len(phold)} ({len(amb)/len(phold):.0%}). Tree accuracy on them: {(amb.tree_join == ~amb.ref_boundary).mean():.1%}; R2: {(amb.r2_join == ~amb.ref_boundary).mean():.1%}; pipeline: {amb.correct.mean():.1%}.\n")
    # dev ambiguous pool for few-shot examples
    pdv = pdev.copy()
    pdv["tree_p_join"] = tree.predict_proba(X(pdv))[:, 1]
    pdv[keep[:9] + ["tree_p_join", "prev_text", "next_text", "prev_ends_sentence", "next_first_indent_em", "prev_indent_em", "next_indent_em", "next2_indent_em", "skipped_lines", "font_change", "prev_right_gap_em", "page_ragged_em"]].to_json(os.path.join(OUT, "dev-pool.jsonl"), orient="records", lines=True)
    open(os.path.join(OUT, "pagebreak.md"), "w").write("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
