import { isAbsolute, join, normalize, resolve } from "node:path";
import { parse } from "yaml";

export type Volume = { path: string; sha256?: string };

export type Recipe = {
  id: string;
  title: string;
  authors?: string;
  published_at?: string;
  source_url?: string;
  /** Where the source lives, relative to the site repo root. */
  repo: string;
  /**
   * Ordered, and the order is semantic: footnote numbering and page indices
   * run continuously across volumes, so reordering changes the output.
   */
  volumes: Volume[];
};

/**
 * Parses and validates a report's build recipe.
 *
 * Which PDFs, in what order, with what metadata was recorded nowhere until
 * this existed — so no report could be regenerated by anyone who was not
 * there the first time.
 *
 * `expectedId` is the directory the file was read from. Cross-checking it
 * against the recipe's own `id` catches the copy-paste that would otherwise
 * ingest one report's PDFs under another report's name.
 */
export function parseRecipe(yamlText: string, expectedId: string): Recipe {
  const raw = parse(yamlText) as Partial<Recipe> | null;
  if (!raw || typeof raw !== "object") throw new Error("recipe is empty");

  if (!raw.id) throw new Error("recipe has no id");
  if (raw.id !== expectedId) {
    throw new Error(`recipe id "${raw.id}" does not match directory "${expectedId}"`);
  }
  if (!raw.title) throw new Error(`${expectedId}: recipe has no title`);
  if (!raw.repo) throw new Error(`${expectedId}: recipe has no repo`);

  const volumes = raw.volumes ?? [];
  if (!volumes.length) throw new Error(`${expectedId}: recipe lists no volumes`);

  for (const volume of volumes) {
    if (!volume?.path) throw new Error(`${expectedId}: a volume has no path`);
    if (isAbsolute(volume.path) || normalize(volume.path).startsWith("..")) {
      throw new Error(
        `${expectedId}: volume path "${volume.path}" escapes the report repo`
      );
    }
  }

  return { ...(raw as Recipe), volumes };
}

/** Absolute path to a volume's PDF, resolved against the report repo. */
export function resolveVolume(recipe: Recipe, volume: Volume, rootDir: string): string {
  return resolve(join(rootDir, recipe.repo, volume.path));
}
